apiVersion: v1
kind: Pod
metadata:
  name: mtq-controller
  namespace: kubevirt
  labels:
    app: mtq-controller
spec:
  serviceAccountName: mtq-controller
  containers:
    - name: mtq-controller
      image: quay.io/bmordeha/kubevirt/mtq_controller:latest
      imagePullPolicy: Always
