apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mtq-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
    - ""
  resources:
    - resourcequotas
  verbs:
    - list
    - watch
    - update
- apiGroups:
    - virtualmachinemigrationresourcequota.kubevirt.io
  resources:
    - virtualmachinemigrationresourcequotas
  verbs:
    - list
    - watch
    - update
    - get
- apiGroups:
    - virtualmachinemigrationresourcequota.kubevirt.io
  resources:
    - virtualmachinemigrationresourcequotas/status
  verbs:
    - update
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstancemigrations
  - virtualmachineinstances
  verbs:
  - list
  - watch