apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mtq-controller
  namespace: kubevirt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mtq-controller
subjects:
- kind: ServiceAccount
  name: mtq-controller
  namespace: kubevirt
