apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualmachinemigrationresourcequotas.kubevirt.io
spec:
  conversion:
    strategy: None
  group: kubevirt.io
  scope: Namespaced
  names:
    categories:
      - all
    kind: VirtualMachineMigrationResourceQuota
    listKind: VirtualMachineMigrationResourceQuotatList
    plural: virtualmachinemigrationresourcequotas
    shortNames:
      - vmmrq
      - vmmrqs
    singular: virtualmachinemigrationresourcequota
  versions:
    - additionalPrinterColumns:
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - jsonPath: .status.phase
          name: Phase
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: VirtualMachineMigrationResourceQuota defines resources that should
            be reserved for a VMI migration
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest internal
                value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object
                represents. Servers may infer this from the endpoint the client submits requests
                to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                hard:
                  additionalProperties:
                    anyOf:
                      - type: integer
                      - type: string
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  description: 'hard is the set of desired hard limits for each named resource.
                    More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/'
                  type: object
              type: object
            status:
              properties:
                conditions:
                  items:
                    description: Condition defines conditions
                    properties:
                      lastProbeTime:
                        format: date-time
                        nullable: true
                        type: string
                      lastTransitionTime:
                        format: date-time
                        nullable: true
                        type: string
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        description: ConditionType is the const type for Conditions
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
                  x-kubernetes-list-type: atomic
                creationTime:
                  format: date-time
                  nullable: true
                  type: string
                migrationsToBlockingResourceQuotas:
                  additionalProperties:
                    items:
                      type: string
                    type: array
                  type: object
                namespaceLocked:
                  nullable: true
                  type: boolean
                originalBlockingResourceQuotas:
                  items:
                    description: ResourceQuota sets aggregate quota restrictions enforced
                      per namespace
                    properties:
                      apiVersion:
                        description: 'APIVersion defines the versioned schema of this representation
                          of an object. Servers should convert recognized schemas to the latest
                          internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                        type: string
                      kind:
                        description: 'Kind is a string value representing the REST resource
                          this object represents. Servers may infer this from the endpoint
                          the client submits requests to. Cannot be updated. In CamelCase.
                          More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                        type: string
                      metadata:
                        description: 'Standard object''s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata'
                        type: object
                      spec:
                        description: Spec defines the desired quota. https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
                        properties:
                          hard:
                            additionalProperties:
                              anyOf:
                                - type: integer
                                - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            description: 'hard is the set of desired hard limits for each
                              named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/'
                            type: object
                          scopeSelector:
                            description: scopeSelector is also a collection of filters like
                              scopes that must match each object tracked by a quota but expressed
                              using ScopeSelectorOperator in combination with possible values.
                              For a resource to match, both scopes AND scopeSelector (if specified
                              in spec), must be matched.
                            properties:
                              matchExpressions:
                                description: A list of scope selector requirements by scope
                                  of the resources.
                                items:
                                  description: A scoped-resource selector requirement is a
                                    selector that contains values, a scope name, and an operator
                                    that relates the scope name and values.
                                  properties:
                                    operator:
                                      description: Represents a scope's relationship to a
                                        set of values. Valid operators are In, NotIn, Exists,
                                        DoesNotExist.
                                      type: string
                                    scopeName:
                                      description: The name of the scope that the selector
                                        applies to.
                                      type: string
                                    values:
                                      description: An array of string values. If the operator
                                        is In or NotIn, the values array must be non-empty.
                                        If the operator is Exists or DoesNotExist, the values
                                        array must be empty. This array is replaced during
                                        a strategic merge patch.
                                      items:
                                        type: string
                                      type: array
                                  required:
                                    - operator
                                    - scopeName
                                  type: object
                                type: array
                            type: object
                          scopes:
                            description: A collection of filters that must match each object
                              tracked by a quota. If not specified, the quota matches all
                              objects.
                            items:
                              description: A ResourceQuotaScope defines a filter that must
                                match each object tracked by a quota
                              type: string
                            type: array
                        type: object
                      status:
                        description: Status defines the actual enforced quota and its current
                          usage. https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
                        properties:
                          hard:
                            additionalProperties:
                              anyOf:
                                - type: integer
                                - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            description: 'Hard is the set of enforced hard limits for each
                              named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/'
                            type: object
                          used:
                            additionalProperties:
                              anyOf:
                                - type: integer
                                - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            description: Used is the current observed total usage of the resource
                              in the namespace.
                            type: object
                        type: object
                    type: object
                  type: array
                  x-kubernetes-list-type: atomic
                phase:
                  type: string
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
