apiVersion: virtualmachinemigrationresourcequota.kubevirt.io/v1alpha1
kind: VirtualMachineMigrationResourceQuota
metadata:
  name: my-vmmrq
  namespace: test
spec:
  additionalMigrationResources:
    cpu: 500m
    memory: 512Mi