apiVersion: mtq.kubevirt.io/v1alpha1
kind: MTQ
metadata:
  name: mtq
spec:
  imagePullPolicy: Always
  infra:
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  workload:
    nodeSelector:
      kubernetes.io/os: linux
