apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mtq-lock-server
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mtq-lock-server
subjects:
- kind: ServiceAccount
  name: mtq-lock-server
  namespace: default
