apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mtq-webhook
rules:
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstancemigrations
  verbs:
  - list
  - watch