---
apiVersion: v1
kind: Service
metadata:
  labels:
    mtq.kubevirt.io: mtq-lock
  name: mtq-lock
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 30100
  selector:
    app: example-webhook
